# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(800, 520)
        Login.setStyleSheet("QLabel#lbl_face_video{\n"
"    border-top-color:#BBBBBB;\n"
"    border-right-color:#BBBBBB;\n"
"    border-bottom-color:#FFFFFF;\n"
"    border-left-color:#FFFFFF;\n"
"    border-style:solid;\n"
"    border-width: 3px;\n"
"    border-radius:20px;\n"
"}")
        self.lbl_title = QtWidgets.QLabel(Login)
        self.lbl_title.setGeometry(QtCore.QRect(220, 30, 360, 81))
        font = QtGui.QFont()
        font.setFamily("华康娃娃体W5(P)")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_version = QtWidgets.QLabel(Login)
        self.lbl_version.setGeometry(QtCore.QRect(370, 110, 60, 20))
        font = QtGui.QFont()
        font.setFamily("华康娃娃体W5(P)")
        self.lbl_version.setFont(font)
        self.lbl_version.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.lbl_subtitle = QtWidgets.QLabel(Login)
        self.lbl_subtitle.setGeometry(QtCore.QRect(330, 150, 140, 21))
        font = QtGui.QFont()
        font.setFamily("华康娃娃体W5")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_subtitle.setFont(font)
        self.lbl_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_subtitle.setObjectName("lbl_subtitle")
        self.line = QtWidgets.QFrame(Login)
        self.line.setGeometry(QtCore.QRect(250, 100, 311, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbl_face_video = QtWidgets.QLabel(Login)
        self.lbl_face_video.setGeometry(QtCore.QRect(160, 200, 480, 320))
        self.lbl_face_video.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_face_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_face_video.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_face_video.setObjectName("lbl_face_video")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(5, 370, 150, 150))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("garbageapp/guis/login/222.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(645, 370, 150, 150))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(1)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("garbageapp/guis/login/333.jpg"))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "垃圾识别智能系统 - 系统智能登录 "))
        self.lbl_title.setText(_translate("Login", "垃圾识别智能系统"))
        self.lbl_version.setText(_translate("Login", "v1.0"))
        self.lbl_subtitle.setText(_translate("Login", "系统智能登录"))
        self.lbl_face_video.setText(_translate("Login", "登录视频"))
